/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as SpecialOrderRouteImport } from './routes/special-order'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as OrderNewRouteImport } from './routes/order.new'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as OrderOrderNumberPaymentRouteImport } from './routes/order.$orderNumber.payment'
import { Route as OrderConfirmationOrderNumberRouteImport } from './routes/order.confirmation.$orderNumber'
import { Route as ApiPublicUploadsIdRouteImport } from './routes/api/public/uploads/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialOrderRoute = SpecialOrderRouteImport.update({
  id: '/special-order',
  path: '/special-order',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderNewRoute = OrderNewRouteImport.update({
  id: '/order/new',
  path: '/order/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderNumberPaymentRoute = OrderOrderNumberPaymentRouteImport.update({
  id: '/order/$orderNumber/payment',
  path: '/order/$orderNumber/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationOrderNumberRoute =
  OrderConfirmationOrderNumberRouteImport.update({
    id: '/order/confirmation/$orderNumber',
    path: '/order/confirmation/$orderNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUploadsIdRoute = ApiPublicUploadsIdRouteImport.update({
  id: '/api/public/uploads/$id',
  path: '/api/public/uploads/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/our-story': typeof OurStoryRoute
  '/special-order': typeof SpecialOrderRoute
  '/track': typeof TrackRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/order/new': typeof OrderNewRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/order/$orderNumber/payment': typeof OrderOrderNumberPaymentRoute
  '/order/confirmation/$orderNumber': typeof OrderConfirmationOrderNumberRoute
  '/api/public/uploads/$id': typeof ApiPublicUploadsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/our-story': typeof OurStoryRoute
  '/special-order': typeof SpecialOrderRoute
  '/track': typeof TrackRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/order/new': typeof OrderNewRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/products': typeof ProductsIndexRoute
  '/order/$orderNumber/payment': typeof OrderOrderNumberPaymentRoute
  '/order/confirmation/$orderNumber': typeof OrderConfirmationOrderNumberRoute
  '/api/public/uploads/$id': typeof ApiPublicUploadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/our-story': typeof OurStoryRoute
  '/special-order': typeof SpecialOrderRoute
  '/track': typeof TrackRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/order/new': typeof OrderNewRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/order/$orderNumber/payment': typeof OrderOrderNumberPaymentRoute
  '/order/confirmation/$orderNumber': typeof OrderConfirmationOrderNumberRoute
  '/api/public/uploads/$id': typeof ApiPublicUploadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/our-story'
    | '/special-order'
    | '/track'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/products'
    | '/categories/$slug'
    | '/order/new'
    | '/products/$slug'
    | '/admin/'
    | '/products/'
    | '/order/$orderNumber/payment'
    | '/order/confirmation/$orderNumber'
    | '/api/public/uploads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/our-story'
    | '/special-order'
    | '/track'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/products'
    | '/categories/$slug'
    | '/order/new'
    | '/products/$slug'
    | '/admin'
    | '/products'
    | '/order/$orderNumber/payment'
    | '/order/confirmation/$orderNumber'
    | '/api/public/uploads/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/our-story'
    | '/special-order'
    | '/track'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/products'
    | '/categories/$slug'
    | '/order/new'
    | '/products/$slug'
    | '/admin/'
    | '/products/'
    | '/order/$orderNumber/payment'
    | '/order/confirmation/$orderNumber'
    | '/api/public/uploads/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  OurStoryRoute: typeof OurStoryRoute
  SpecialOrderRoute: typeof SpecialOrderRoute
  TrackRoute: typeof TrackRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  OrderNewRoute: typeof OrderNewRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  OrderOrderNumberPaymentRoute: typeof OrderOrderNumberPaymentRoute
  OrderConfirmationOrderNumberRoute: typeof OrderConfirmationOrderNumberRoute
  ApiPublicUploadsIdRoute: typeof ApiPublicUploadsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-order': {
      id: '/special-order'
      path: '/special-order'
      fullPath: '/special-order'
      preLoaderRoute: typeof SpecialOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/new': {
      id: '/order/new'
      path: '/order/new'
      fullPath: '/order/new'
      preLoaderRoute: typeof OrderNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderNumber/payment': {
      id: '/order/$orderNumber/payment'
      path: '/order/$orderNumber/payment'
      fullPath: '/order/$orderNumber/payment'
      preLoaderRoute: typeof OrderOrderNumberPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/confirmation/$orderNumber': {
      id: '/order/confirmation/$orderNumber'
      path: '/order/confirmation/$orderNumber'
      fullPath: '/order/confirmation/$orderNumber'
      preLoaderRoute: typeof OrderConfirmationOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/uploads/$id': {
      id: '/api/public/uploads/$id'
      path: '/api/public/uploads/$id'
      fullPath: '/api/public/uploads/$id'
      preLoaderRoute: typeof ApiPublicUploadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  OurStoryRoute: OurStoryRoute,
  SpecialOrderRoute: SpecialOrderRoute,
  TrackRoute: TrackRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  OrderNewRoute: OrderNewRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  OrderOrderNumberPaymentRoute: OrderOrderNumberPaymentRoute,
  OrderConfirmationOrderNumberRoute: OrderConfirmationOrderNumberRoute,
  ApiPublicUploadsIdRoute: ApiPublicUploadsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
